// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gsdetal.DBViewModel;

#nullable disable

namespace gsdetal.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250313063037_3change")]
    partial class _3change
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("gsdetal.Models.Itemdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.Property<string>("temp")
                        .HasColumnType("TEXT");

                    b.Property<string>("thumbnailpath")
                        .HasColumnType("TEXT");

                    b.Property<string>("thumbnailurl")
                        .HasColumnType("TEXT");

                    b.Property<string>("tip")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("url", "color", "size")
                        .IsUnique();

                    b.ToTable("Itemdetails", (string)null);
                });

            modelBuilder.Entity("gsdetal.Models.Url", b =>
                {
                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.Property<string>("order")
                        .HasColumnType("TEXT");

                    b.Property<string>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("templatetype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatetime")
                        .HasColumnType("TEXT");

                    b.HasKey("url");

                    b.ToTable("Urls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
